### ISSUE TITLE
Error relocating /usr/bin/curl: curl_easy_nextheader: symbol not found

### ISSUE THREAD

**Issue by scott-doyland-burrows** [GetTerminus/terraform-pr-commenter#15]
Hi,

I switched to this fork of ```robburger/terraform-pr-commenter@v1``` but still get the curl issues as below

![image](https://user-images.githubusercontent.com/61512176/237019550-98dbd6d5-ff32-4f8e-8117-6c5fe95156eb.png)

**Comment by ms-ati** [comment]
Is this working?

**Comment by ms-ati** [comment]
Wow thank you @liamfit I'll try this! Can you share a bit about how `inputs.comment-on-plan` works, this looks different from the examples?
